version: '3.8'  # You can adjust the version as needed

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: my_db_maria_person
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"